pj_name: Vox_IEMO_REVISION
memo: emo(CE)_id(Arc)_load
repeat_3_sec: true
emo_hs_linear: linear
alpha_loss: 1
beta_loss: 1
start_patience_epoch: 30
patience_limit: 10
init_id_with_trainset: false
id_weight: /home/ubuntu/Dropbox/23_for_revision/vox_id/hs_1000_230208_1652/best_model.pt
id_net_freeze: freeze
id_pool_freeze: true
id_hs_linear: hs
fin_channel: 768
pool: attn_max
pool_head: 3
id_scale: 30
id_margin: 0.3
emo_scale: 30
emo_margin: 0.3
total_epochs: 100
accum_grad: 4
cuda_num: 1
seed: 1000
batch_sizes: 6
lr: 1.0e-05
weight_decay: 1.0e-08
max_grad: 100.0
adam_beta1: 0.9
adam_beta2: 0.98
adam_eps: 1.0e-06
gamma: 0.98
max_sec: 15
vad: false
data_mode: all
concat_ExcHap: true
concat_FruAng: false
use_class:
- ang
- hapexc
- sad
- neu
data_file: /home/ubuntu/Desktop/MY_GITHUB/VAD_net/emo_vad_sec.csv
fold_num: 1
emo_weight: /home/ubuntu/Dropbox/Using Speaker-specific Emotion Representations in
  wav2vec 2.0-based modules for SER/Vox_IEMO_REVISION/main_CE_only_emo/pool_3/1_230531_1323/best_model.pt
