pj_name: Vox_IEMO(3)
repeat_3_sec: true
emo_hs_linear: hs
alpha_loss: 1
beta_loss: 1
start_patience_epoch: 50
patience_limit: 10
fin_channel: 768
pool: attn_max
pool_head: 1
emo_scale: 30
emo_margin: 0.3
total_epochs: 150
accum_grad: 4
cuda_num: 1
seed: 1000
batch_sizes: 6
lr: 3.0000000000000004e-05
weight_decay: 1.0e-08
max_grad: 100.0
adam_beta1: 0.9
adam_beta2: 0.98
adam_eps: 1.0e-06
gamma: 0.98
max_sec: 15
vad: false
data_mode: all
concat_ExcHap: true
concat_FruAng: false
use_class:
- ang
- hapexc
- sad
- neu
data_file: /home/cvnar2/Desktop/ssd/somin/vad_net/emo_vad_sec.csv
fold_num: 1
