memo: iden
pj_name: Vox
hs_linear: linear
patience_limit: 5
fin_channel: 768
pool: attn_max
pool_head: 1
scale: 30
margin: 0.3
total_epochs: 50
accum_grad: 2
cuda_num: 1
seed: 1000
batch_sizes: 16
lr: 3.0000000000000004e-05
weight_decay: 1.0e-08
max_grad: 100.0
adam_beta1: 0.9
adam_beta2: 0.98
adam_eps: 1.0e-06
gamma: 0.98
max_sec: 15
